'Solution'
mate-academy/py-distance-class pull request #1121
Opened 2024-03-22 17:10 UTC by March1205

2024-03-22 18:34 UTC, vsmutok requested changes

2024-03-22 18:34 UTC, vsmutok commented on app/main.py
> +    def __init__(self, km: float) -> None:
```suggestion
    def __init__(self, km: float | int) -> None:
```

2024-03-22 18:34 UTC, vsmutok commented on app/main.py
> +    def __add__(self, other: "Distance") -> "Distance":
```suggestion
    def __add__(self, other: Distance | int | float) -> Distance:
```

2024-03-22 18:34 UTC, vsmutok commented on app/main.py
> +    def __add__(self, other: "Distance") -> "Distance":
fix everywhere

2024-03-22 18:34 UTC, vsmutok commented on app/main.py
> +        else:
else redundant here

2024-03-23 08:07 UTC, March1205 commented
I couldn't use '|' operator so used 'Union' instead, as my code kept failing without it. I also tried to do Distance without quotes but I kept getting NameError as name couldn't be defined and even by defining it at the end I still had to use quotes in most parts. If you could suggest something to complete this code as you told me, please do, because I might be missing some things.

2024-03-24 15:37 UTC, vsmutok requested changes

2024-03-24 15:37 UTC, vsmutok commented on app/main.py
> +        else:
`else` redundant in this case

2024-03-24 15:37 UTC, vsmutok commented
> I couldn't use '|' operator so used 'Union' instead, as my code kept failing without it. I also tried to do Distance without quotes but I kept getting NameError as name couldn't be defined and even by defining it at the end I still had to use quotes in most parts. If you could suggest something to complete this code as you told me, please do, because I might be missing some things.


try use:
```python
from __future__ import annotations
```

2024-04-23 07:47 UTC, closed without merging