Task 7
mate-academy/py-distance-class pull request #1333
Opened 2024-07-25 11:56 UTC by Poznanskyi

2024-07-25 12:14 UTC, MNDonut requested changes

2024-07-25 12:14 UTC, MNDonut commented on app/main.py
> +    def __add__(self, other: "Distance") -> "Distance":
but other can be int or float as well
fix everywhere

2024-07-25 12:14 UTC, MNDonut commented on app/main.py
> +        else:
you don't need else because if and elif have return.
fix everywhere

2024-07-25 13:00 UTC, MNDonut requested changes

2024-07-25 13:00 UTC, MNDonut commented on app/main.py
> +    def __add__(self, other: float) -> "Distance":
but other can be Distance and int as well because you do these checks below

2024-07-25 13:00 UTC, MNDonut commented on app/main.py
> +    def __iadd__(self, other: float) -> "Distance":
but other can be Distance and int as well because you do these checks below

2024-07-25 13:00 UTC, MNDonut commented on app/main.py
>      def __mul__(self, factor: float) -> "Distance":
but other can be int as well because you do these checks below

2024-07-25 13:00 UTC, MNDonut commented on app/main.py
>      def __truediv__(self, divisor: float) -> "Distance":
but other can be int as well because you do these checks below

2024-07-25 13:00 UTC, MNDonut commented on app/main.py
>      def __lt__(self, other: "Distance") -> bool:
but other can be int and float as well because you do these checks below

2024-07-25 13:00 UTC, MNDonut commented on app/main.py
>      def __le__(self, other: "Distance") -> bool:
but other can be int and float as well because you do these checks below

2024-07-25 13:00 UTC, MNDonut commented on app/main.py
>      def __ge__(self, other: "Distance") -> bool:
but other can be int and float as well because you do these checks below

2024-07-29 08:58 UTC, MNDonut requested changes
You didn't push a new commit after the comments I left

2024-07-29 11:43 UTC, MNDonut requested changes

2024-07-29 11:43 UTC, MNDonut commented on app/main.py
> +    def __add__(self, other: Union["Distance", int, float]) -> "Distance":
1. You can use | instead of Union
2. No need to use quotes, import annotations from future and everything will work

2024-07-29 13:51 UTC, oliasymak24 requested changes

2024-07-29 13:51 UTC, oliasymak24 commented on app/main.py
> +    def __add__(self, other: Distance | int | float) -> "Distance":
No need to use quotes, check in all places

2024-07-29 13:51 UTC, oliasymak24 commented on app/main.py
> +        if isinstance(other, Distance):
For better optimization you can try to create a separate method for your code duplicates in all function for checking

2024-07-29 14:15 UTC, oliasymak24 approved these changes
Good job!

2025-05-15 12:30 UTC, closed without merging