Solution
mate-academy/py-distance-class pull request #1382
Opened 2024-08-28 13:45 UTC by MahdaArtem-py

There is a question how to optimize the code. In tests where the second argument is a num, an error occurs: "AttributeError: 'int' object has no attribute 'km'". I got around this problem by adding instance variable .real. What is the best way to solve this problem?

2024-08-28 18:49 UTC, vsmutok requested changes

2024-08-28 18:49 UTC, vsmutok commented on app/main.py
> +    def __add__(self, other: Distance) -> Distance:
```suggestion
    def __add__(self, other: Distance | int | float) -> Distance:
```

2024-08-29 12:55 UTC, vasylhnatiuk requested changes

2024-08-29 12:55 UTC, vasylhnatiuk commented on app/main.py
> +    def __add__(self, other: Distance | int | float) -> Distance:
do `other: Distance | int | float` in each method

2024-08-30 12:38 UTC, vasylhnatiuk approved these changes

2026-06-19 18:01 UTC, closed without merging