Solution_v2_
mate-academy/py-distance-class pull request #239
Opened 2022-10-13 09:33 UTC by ArtMot99

2022-10-13 09:34 UTC, ArtMot99 commented
What's wrong?! Why is he cursing?!

2022-10-13 11:25 UTC, IvanRamyk requested changes

2022-10-13 11:25 UTC, IvanRamyk commented on app/main.py
> +        other_distance = other if isinstance(other, (int, float)) else other.km
`other` instance couldn't have type `Distance`

2022-10-13 11:25 UTC, IvanRamyk commented on app/main.py
> +        other_distance = other if isinstance(other, (int, float)) else other.km
same here

2022-10-14 19:11 UTC, IvanRamyk approved these changes
Well done!

2024-03-12 16:59 UTC, closed without merging