solution
mate-academy/py-distance-class pull request #376
Opened 2023-02-07 08:13 UTC by usrofgh

2023-02-07 14:05 UTC, Yevheniy-Lototskiy approved these changes

2023-02-07 17:55 UTC, wQuelS requested changes
Code is nice, just one small comment

2023-02-07 17:55 UTC, wQuelS commented on app/main.py
> +    def __add__(self, another_distance: Distance | int | float) -> Distance:
by convention we use `other` in such cases. Fix everywhere

2023-02-08 15:36 UTC, Y-Havryliv approved these changes
well done!

2025-12-11 16:34 UTC, closed without merging