py-distance-class
mate-academy/py-distance-class pull request #504
Opened 2023-04-30 16:30 UTC by muriakula

2023-04-30 16:35 UTC, Bohdan-Salamakha commented on app/main.py
> +    def __add__(self, other: Any) -> Any:
other can be int, float or Distance
return type is Distance

2023-04-30 16:35 UTC, Bohdan-Salamakha commented on app/main.py
> +    def __iadd__(self, other: Any) -> Any:
other can be int, float or Distance
return type is Distance

2023-04-30 16:35 UTC, Bohdan-Salamakha commented on app/main.py
> +    def __mul__(self, other: (int, float)) -> Any:
other can be int, float or Distance
return type is Distance

2023-04-30 16:35 UTC, Bohdan-Salamakha commented on app/main.py
> +    def __truediv__(self, other: (int, float)) -> Any:
other can be int, float or Distance
return type is Distance

2023-04-30 16:36 UTC, Bohdan-Salamakha commented on app/main.py
> +    def __eq__(self, other: Any) -> bool:
other can be int, float or Distance

2023-04-30 16:36 UTC, Bohdan-Salamakha commented on app/main.py
> +    def __gt__(self, other: Any) -> bool:
other can be int, float or Distance

2023-04-30 16:36 UTC, Bohdan-Salamakha commented on app/main.py
> +    def __ge__(self, other: Any) -> bool:
other can be int, float or Distance

2023-04-30 16:36 UTC, Bohdan-Salamakha commented on app/main.py
> +    def __lt__(self, other: Any) -> bool:
other can be int, float or Distance

2023-04-30 16:36 UTC, Bohdan-Salamakha commented on app/main.py
> +    def __le__(self, other: Any) -> bool:
other can be int, float or Distance

2023-04-30 16:36 UTC, Bohdan-Salamakha commented on app/main.py
> +        else:
remove redundant "else"

2023-04-30 16:36 UTC, Bohdan-Salamakha commented on app/main.py
> +        else:
remove redundant "else"

2023-04-30 16:37 UTC, Bohdan-Salamakha commented on app/main.py
> +            return Distance(new_distance)
add condition for Distance

2023-04-30 16:37 UTC, Bohdan-Salamakha commented on app/main.py
> +        else:
remove redundant "else"

2023-04-30 16:37 UTC, Bohdan-Salamakha commented on app/main.py
> +        else:
remove redundant "else"

2023-04-30 16:37 UTC, Bohdan-Salamakha commented on app/main.py
> +        else:
remove redundant "else"

2023-04-30 16:37 UTC, Bohdan-Salamakha commented on app/main.py
> +        else:
remove redundant "else"

2023-04-30 16:37 UTC, Bohdan-Salamakha commented on app/main.py
> +            return Distance(new_distance)
add condition for Distance

2023-04-30 16:38 UTC, Bohdan-Salamakha requested changes
v1

2023-05-01 15:14 UTC, olena-hul requested changes

2023-05-01 15:14 UTC, olena-hul commented on app/main.py
> +        if type(other) == int or type(other) == float:
Use the opposite condition: `if isinstance(other, Distance)`
It's better to use `isinstance` than `type` for type checks

2024-10-29 10:10 UTC, closed without merging