Solution
mate-academy/py-distance-class pull request #534
Opened 2023-05-26 12:31 UTC by gleblitvinenko

2023-05-27 10:57 UTC, ArsenPidhoretskyi requested changes

2023-05-27 10:57 UTC, ArsenPidhoretskyi commented on app/main.py
> +        elif isinstance(other, (int, float)):
No need to use elif. Due to type annotations in this step it will be always int or float

2023-05-27 10:57 UTC, ArsenPidhoretskyi commented on app/main.py
> +    def __add__(self, other: "Distance") -> "Distance":
int and float also possible

2023-05-27 10:57 UTC, ArsenPidhoretskyi commented on app/main.py
> +    def __iadd__(self, other: "Distance") -> "Distance":
int and float also possible

2023-05-27 10:57 UTC, ArsenPidhoretskyi commented on app/main.py
> +        elif isinstance(other, (int, float)):
just else:

2023-05-27 10:57 UTC, ArsenPidhoretskyi commented on app/main.py
> +        if isinstance(other, (int, float)):
This check is not needed. Due to type annotations it always true
The same with mul

2023-05-27 10:57 UTC, ArsenPidhoretskyi commented on app/main.py
> +        elif isinstance(other, (int, float)):
fix in all places

2023-05-27 10:57 UTC, ArsenPidhoretskyi commented on app/main.py
> +    def __iadd__(self, other: "Distance") -> "Distance":
fix in all places

2023-05-27 12:40 UTC, vsmutok requested changes

2023-05-27 12:40 UTC, vsmutok commented on app/main.py
> +        else:
Redundant `else`

fix here and in other places

2023-05-27 13:10 UTC, vsmutok approved these changes
Great 👍

2023-05-29 12:52 UTC, Abnormaltype approved these changes

2023-05-29 13:22 UTC, ihor-jpeg approved these changes

2023-05-29 13:26 UTC, ihor-jpeg approved these changes

2026-03-10 17:47 UTC, closed without merging