Solution
mate-academy/py-distance-class pull request #566
Opened 2023-06-01 15:00 UTC by mwellick

2023-06-01 16:26 UTC, Bohdan-Salamakha commented on app/main.py
> +        elif isinstance(other, int | float):
remove redundant "elif" check

2023-06-01 16:26 UTC, Bohdan-Salamakha commented on app/main.py
> +        elif isinstance(other, (int | float)):
remove redundant "elif" check

2023-06-01 17:50 UTC, EdAlekseiev requested changes

2023-06-02 07:25 UTC, olena-hul requested changes

2023-06-02 07:25 UTC, olena-hul commented on app/main.py
> +    def __truediv__(self, other: Union["Distance", int | float]) -> "Distance":
other can be only int or float in __truediv__

2023-06-02 07:25 UTC, olena-hul commented on app/main.py
> +    def __mul__(self, other: Union["Distance", int | float]) -> "Distance":
other can be only int or float in __mul__

2023-06-02 09:49 UTC, Bohdan-Salamakha approved these changes

2024-02-26 07:36 UTC, closed without merging