Develop
mate-academy/py-distance-class pull request #587
Opened 2023-06-20 19:33 UTC by NazarKravchenk0

2023-06-21 08:03 UTC, Bohdan-Salamakha requested changes
1
don't change flake8 settings
2
add typehint for "other"

2024-03-14 18:29 UTC, EdAlekseiev requested changes

2024-03-14 18:29 UTC, EdAlekseiev commented on app/main.py
> +    def __add__(self, other: "Distance") -> "Distance":
Other can be int and float too. Fix everywhere
```suggestion
    def __add__(self, other: "Distance" | int | float) -> "Distance":
```

2025-08-27 07:03 UTC, vsmutok requested changes

2025-08-27 07:03 UTC, vsmutok commented on app/main.py
> +    def __add__(self, other: "Distance") -> "Distance":
```suggestion
    def __add__(self, other: Distance | int | float) -> Distance:
```

2025-08-27 07:03 UTC, vsmutok commented on app/main.py
> +        else:
`else` redundant here

2026-01-27 16:48 UTC, closed without merging