Solution_py_distance_class
mate-academy/py-distance-class pull request #727
Opened 2023-09-12 20:04 UTC by VladKrit-commits

2023-09-13 10:00 UTC, Dimosphen1 requested changes
Several changes were requested.

2023-09-13 10:00 UTC, Dimosphen1 commented on app/main.py
> +        return self.km <= other.km
You could rely on the implementation of other methods such as `__gt__` here and in other methods as well.

2023-09-13 10:43 UTC, VladKrit-commits commented
I made it(i hope so:)) in the "...(changed)" commit

2023-09-15 18:50 UTC, viktoria-rybenchuk reviewed
Good job!

2023-09-16 10:20 UTC, pavlejviki requested changes

2023-09-16 10:20 UTC, pavlejviki commented on app/main.py
> +        elif isinstance:
```suggestion
        elif isinstance(other, Distance):
```

2023-09-16 10:20 UTC, pavlejviki commented on app/main.py
> +        return Distance(self.km / other.km)
other can't be Distance instance so this return is redundant

2023-09-16 10:20 UTC, pavlejviki commented on app/main.py
> +    def __le__(self, other: int | float | Distance) -> bool:
You can use previously created magic method here(and in ge as well) to simplify your code. e.g. return not self > other

2023-09-16 20:56 UTC, VladKrit-commits commented
Done in solution(changed_2)

2023-10-02 10:05 UTC, closed without merging