Solution
mate-academy/py-distance-class pull request #75
Opened 2022-06-15 18:42 UTC by VladyslavKlevanskyi

2022-06-16 05:38 UTC, Abnormaltype requested changes

2022-06-16 05:38 UTC, Abnormaltype commented on app/main.py
> +        else:
remove unnecessary `else`

2022-06-16 05:38 UTC, Abnormaltype commented on app/main.py
> +        else:
remove unnecessary `else`

2022-06-16 05:38 UTC, Abnormaltype commented on app/main.py
> +        else:
remove unnecessary `else`

2022-06-16 05:38 UTC, Abnormaltype commented on app/main.py
> +        else:
remove unnecessary `else`

2022-06-16 05:38 UTC, Abnormaltype commented on app/main.py
> +        else:
remove unnecessary `else`

2022-06-16 05:38 UTC, Abnormaltype commented on app/main.py
> +        else:
remove unnecessary `else`

2022-06-16 05:38 UTC, Abnormaltype commented on app/main.py
> +            return True if self.km >= other else False
Try return only `self.km >= other` and fix it, also in other cases

2022-06-16 10:50 UTC, Abnormaltype requested changes

2022-06-16 10:50 UTC, Abnormaltype commented on app/main.py
> +        else:
Last one

2022-06-16 11:12 UTC, Abnormaltype approved these changes
Good job!

2022-08-09 13:41 UTC, VladyslavKlevanskyi commented
Hi! My progress on site _mate.academy_ is gone. Can you approve it again please?

2022-08-09 13:41 UTC, Abnormaltype reviewed
done)

2025-01-16 03:21 UTC, closed without merging