Implement pi-distance-class
mate-academy/py-distance-class pull request #762
Opened 2023-10-03 14:50 UTC by SevKrok

2023-10-03 16:29 UTC, RabenkoYevhenii approved these changes
But everything else is perfect ;)

2023-10-03 17:42 UTC, SevKrok commented on app/main.py
> +        elif isinstance(other, (int, float)):
I'm playing it safe)))

2023-10-05 10:54 UTC, fsocie7y requested changes

2023-10-05 10:54 UTC, fsocie7y commented on app/main.py
> +            return self.km >= other
try to rewrite these two methods in one line each. Use previously created magic methods
Hint: <= is the same as not >

2023-10-05 10:54 UTC, fsocie7y commented on app/main.py
> +            return self.km == other
You can skip second check here and directly return from this point
in one case above too

2023-10-05 10:54 UTC, fsocie7y commented on app/main.py
> +        elif isinstance(other, (int, float)):
here, as Yevhenii gives advice

2023-10-05 10:54 UTC, fsocie7y commented on app/main.py
> +        elif isinstance(other, (int, float)):
here, as Yevhenii gives advice

2023-10-05 10:54 UTC, fsocie7y commented on app/main.py
> +        elif isinstance(other, (int, float)):
here, as Yevhenii gives advice

2023-10-05 10:54 UTC, fsocie7y commented on app/main.py
> +        elif isinstance(other, (int, float)):
here, as Yevhenii gives advice

2023-10-05 14:54 UTC, fsocie7y approved these changes
GJ 🥇

2023-10-11 09:47 UTC, closed without merging