'Solution'
mate-academy/py-distance-class pull request #99
Opened 2022-07-21 14:39 UTC by Viktor-Beniukh

2022-07-22 10:05 UTC, IvanRamyk requested changes

2022-07-22 10:05 UTC, IvanRamyk commented on app/main.py
> +        if isinstance(self.km, int):
And if it's a float value?

2022-07-22 10:05 UTC, IvanRamyk commented on app/main.py
> +        if isinstance(self.km, int):
I believe you don't need this if-statement

2022-07-25 08:36 UTC, Abnormaltype requested changes

2022-07-25 08:36 UTC, Abnormaltype commented on app/main.py
> +        if isinstance(other, int):
And if it's a float value?

2022-07-25 08:36 UTC, Abnormaltype commented on app/main.py
> +        if isinstance(other, int):
the same here

2022-07-25 08:36 UTC, Abnormaltype commented on app/main.py
> +        if isinstance(other, int):
the same here

2022-07-25 08:36 UTC, Abnormaltype commented on app/main.py
> +        if isinstance(other, int):
the same here

2022-07-25 12:55 UTC, closed without merging